const allPlayers = [
	[
		{
			name: 'Eileen Feeney',
			country: 'Hong Kong',
			age: 37,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/494.jpg',
			stamina: 70,
			speed: 79,
			dribbling: 85,
			strength: 56,
			power: 74,
			position: 'Midfielder',
		},
		{
			name: 'Ora Harber',
			country: 'Pitcairn Islands',
			age: 17,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/581.jpg',
			stamina: 84,
			speed: 64,
			dribbling: 67,
			strength: 76,
			power: 71,
			position: 'Defender',
		},
		{
			name: 'Velma Beahan',
			country: 'Cocos (Keeling) Islands',
			age: 18,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/409.jpg',
			stamina: 66,
			speed: 57,
			dribbling: 83,
			strength: 81,
			power: 55,
			position: 'Goal Keeper',
		},
		{
			name: 'Mandy Sipes',
			country: 'Cameroon',
			age: 19,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/819.jpg',
			stamina: 60,
			speed: 79,
			dribbling: 96,
			strength: 76,
			power: 75,
			position: 'Midfielder',
		},
		{
			name: 'Kurt Bruen',
			country: 'Hong Kong',
			age: 27,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1013.jpg',
			stamina: 56,
			speed: 70,
			dribbling: 77,
			strength: 55,
			power: 79,
			position: 'Stricker',
		},
	],
	[
		{
			name: 'Sara Koch',
			country: 'Swaziland',
			age: 19,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/177.jpg',
			stamina: 70,
			speed: 69,
			dribbling: 55,
			strength: 58,
			power: 74,
			position: 'Left Winger',
		},
		{
			name: 'Cary Rogahn',
			country: 'Eritrea',
			age: 19,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/851.jpg',
			stamina: 69,
			speed: 60,
			dribbling: 70,
			strength: 61,
			power: 76,
			position: 'Stricker',
		},
		{
			name: 'Traci Hintz',
			country: 'Cook Islands',
			age: 34,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/26.jpg',
			stamina: 89,
			speed: 50,
			dribbling: 63,
			strength: 65,
			power: 58,
			position: 'Goal Keeper',
		},
		{
			name: 'Dr. Lorene Kuhlman',
			country: 'South Georgia and the South Sandwich Islands',
			age: 37,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/434.jpg',
			stamina: 74,
			speed: 68,
			dribbling: 63,
			strength: 58,
			power: 71,
			position: 'Stricker',
		},
		{
			name: 'Martin Schuppe',
			country: 'Svalbard & Jan Mayen Islands',
			age: 24,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/927.jpg',
			stamina: 55,
			speed: 69,
			dribbling: 58,
			strength: 88,
			power: 61,
			position: 'Defender',
		},
	],
	[
		{
			name: 'Alonzo Bashirian',
			country: 'Cayman Islands',
			age: 32,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1218.jpg',
			stamina: 83,
			speed: 83,
			dribbling: 89,
			strength: 78,
			power: 98,
			position: 'Midfielder',
		},
		{
			name: 'Craig Lueilwitz',
			country: 'Eritrea',
			age: 30,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/351.jpg',
			stamina: 76,
			speed: 83,
			dribbling: 64,
			strength: 79,
			power: 85,
			position: 'Midfielder',
		},
		{
			name: 'Lynne Lockman',
			country: 'Belize',
			age: 26,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/843.jpg',
			stamina: 94,
			speed: 70,
			dribbling: 69,
			strength: 58,
			power: 78,
			position: 'Left Winger',
		},
		{
			name: 'Tyrone Crona',
			country: 'Cape Verde',
			age: 30,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/304.jpg',
			stamina: 98,
			speed: 62,
			dribbling: 65,
			strength: 90,
			power: 63,
			position: 'Goal Keeper',
		},
		{
			name: 'Alton Renner DVM',
			country: 'Nepal',
			age: 33,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/753.jpg',
			stamina: 83,
			speed: 65,
			dribbling: 65,
			strength: 89,
			power: 65,
			position: 'Right Winger',
		},
	],
	[
		{
			name: 'Cynthia Huels',
			country: 'Bermuda',
			age: 33,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/196.jpg',
			stamina: 66,
			speed: 81,
			dribbling: 92,
			strength: 90,
			power: 73,
			position: 'Goal Keeper',
		},
		{
			name: 'Shawna Haag',
			country: 'Jersey',
			age: 34,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/952.jpg',
			stamina: 69,
			speed: 84,
			dribbling: 66,
			strength: 88,
			power: 57,
			position: 'Central Defenders',
		},
		{
			name: 'Lionel Aufderhar',
			country: 'Bermuda',
			age: 25,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/60.jpg',
			stamina: 84,
			speed: 55,
			dribbling: 77,
			strength: 71,
			power: 63,
			position: 'Left Winger',
		},
		{
			name: 'Scott Leannon',
			country: 'New Caledonia',
			age: 35,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/906.jpg',
			stamina: 76,
			speed: 77,
			dribbling: 88,
			strength: 91,
			power: 78,
			position: 'Central Defenders',
		},
		{
			name: 'Larry Quitzon',
			country: 'Iceland',
			age: 32,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/995.jpg',
			stamina: 98,
			speed: 76,
			dribbling: 70,
			strength: 63,
			power: 74,
			position: 'Stricker',
		},
	],
	[
		{
			name: 'Mabel Grady',
			country: 'Vanuatu',
			age: 28,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1030.jpg',
			stamina: 81,
			speed: 60,
			dribbling: 91,
			strength: 72,
			power: 79,
			position: 'Goal Keeper',
		},
		{
			name: 'Esther Mitchell',
			country: 'Dominican Republic',
			age: 29,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/552.jpg',
			stamina: 76,
			speed: 77,
			dribbling: 60,
			strength: 75,
			power: 56,
			position: 'Stricker',
		},
		{
			name: 'Emilio Kris',
			country: 'Timor-Leste',
			age: 19,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/161.jpg',
			stamina: 86,
			speed: 94,
			dribbling: 97,
			strength: 92,
			power: 57,
			position: 'Left Winger',
		},
		{
			name: 'Kurt Klein',
			country: 'Indonesia',
			age: 17,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/626.jpg',
			stamina: 88,
			speed: 96,
			dribbling: 68,
			strength: 62,
			power: 85,
			position: 'Defender',
		},
		{
			name: 'Gertrude Upton MD',
			country: 'Mauritania',
			age: 18,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/371.jpg',
			stamina: 95,
			speed: 59,
			dribbling: 79,
			strength: 66,
			power: 60,
			position: 'Midfielder',
		},
	],
	[
		{
			name: 'Arthur Hudson IV',
			country: 'Timor-Leste',
			age: 32,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/20.jpg',
			stamina: 50,
			speed: 50,
			dribbling: 50,
			strength: 50,
			power: 50,
			position: 'Midfielder',
		},
		{
			name: 'Cassandra Moen',
			country: 'Tunisia',
			age: 27,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/557.jpg',
			stamina: 50,
			speed: 50,
			dribbling: 50,
			strength: 50,
			power: 50,
			position: 'Goal Keeper',
		},
		{
			name: 'Vincent Haley',
			country: 'Russian Federation',
			age: 33,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/111.jpg',
			stamina: 50,
			speed: 50,
			dribbling: 50,
			strength: 50,
			power: 50,
			position: 'Central Defenders',
		},
		{
			name: 'Pablo Harvey',
			country: 'Mauritania',
			age: 20,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/427.jpg',
			stamina: 50,
			speed: 50,
			dribbling: 50,
			strength: 50,
			power: 50,
			position: 'Midfielder',
		},
		{
			name: 'Gordon Satterfield II',
			country: 'Philippines',
			age: 19,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/791.jpg',
			stamina: 50,
			speed: 50,
			dribbling: 50,
			strength: 50,
			power: 50,
			position: 'Left Winger',
		},
	],
	[
		{
			name: 'Zachary Okuneva',
			country: 'Uzbekistan',
			age: 28,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/28.jpg',
			stamina: 99,
			speed: 99,
			dribbling: 99,
			strength: 99,
			power: 99,
			position: 'Central Defenders',
		},
		{
			name: 'Glenda Schulist',
			country: 'Turkmenistan',
			age: 26,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/161.jpg',
			stamina: 90,
			speed: 97,
			dribbling: 90,
			strength: 96,
			power: 98,
			position: 'Stricker',
		},
		{
			name: 'Ms. Danielle Powlowski',
			country: 'Maldives',
			age: 36,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/678.jpg',
			stamina: 99,
			speed: 98,
			dribbling: 97,
			strength: 96,
			power: 96,
			position: 'Right Winger',
		},
		{
			name: 'Gerald Lueilwitz',
			country: 'Chile',
			age: 35,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/142.jpg',
			stamina: 94,
			speed: 99,
			dribbling: 96,
			strength: 98,
			power: 99,
			position: 'Right Winger',
		},
		{
			name: 'Emily Schiller',
			country: "Lao People's Democratic Republic",
			age: 36,
			avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/902.jpg',
			stamina: 95,
			speed: 96,
			dribbling: 93,
			strength: 90,
			power: 100,
			position: 'Goal Keeper',
		},
	],
];

module.exports = { allPlayers };
